# [default_session]
# startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "configs"
path = "~/.local/share/chezmoi"
# startup_command = "nvim tmux.conf"

[[session]]
name = "root-with-notes"
path = "~/Desktop"
startup_script="~/.local/bin/tmux_root_with_notes"
