# all of my keybindings are managed by tmux/nvim, so anything that alacritty adds is redundant, also vi mode is a nuisance
# see https://alacritty.org/config-alacritty-bindings.html

[keyboard]
bindings = [
	{ key= "C", mods = "Command", chars = "\uE000" },
	{ key= "N", mods = "Command", chars = "\uE001" },
	{ key= "P", mods = "Command", chars = "\uE002" },
	# { key= "=", mods = "Command", chars = "\uE003" },
	{ key= "T", mods = "Command", chars = "\uE004" },
	{ key= "G", mods = "Control", chars = "\uE005" },
	# general
	# { key = "Paste", action = "ReceiveChar" },
	{ key = "Copy", action = "ReceiveChar" },
	{ key = "L", mods = "Control", action = "ReceiveChar" },
	# { key = "Paste", mode = "Vi|Search", action = "ReceiveChar" },
	{ key = "L", mods = "Control", mode = "~Vi|~Search", action = "ReceiveChar" },
	{ key = "PageUp", mods = "Shift", mode = "~Alt", action = "ReceiveChar"},
	{ key = "PageDown", mods = "Shift", mode = "~Alt", action = "ReceiveChar"},
	{ key = "Home", mods = "Shift", mode = "~Alt", action = "ReceiveChar"},
	{ key = "End", mods = "Shift", mode = "~Alt", action = "ReceiveChar"},
	# vi mode
	{ key = "Space", mods = "Shift|Control", mode = "~Search", action = "ReceiveChar"},
	{ key = "Space", mods = "Shift|Control", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "Escape", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "I", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "I", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "C", mods = "Control", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "Y", mods = "Control", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "E", mods = "Control", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "G", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "G", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "B", mods = "Control", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "F", mods = "Control", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "U", mods = "Control", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "D", mods = "Control", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "Y", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "Y", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "Copy", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "V", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "V", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "V", mods = "Control", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "V", mods = "Alt", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "Enter", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "Z", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "F", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "F", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "T", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "T", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = ";", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = ",", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "K", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "J", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "H", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "L", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "ArrowUp", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "ArrowDown", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "ArrowLeft", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "ArrowRight", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "0", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "$", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "^", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "H", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "M", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "L", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "B", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "W", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "E", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "B", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "W", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "E", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "%", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "/", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "?", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "N", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "N", mods = "Shift", mode = "Vi|~Search", action = "ReceiveChar"},
	# search mode
	{ key = "Enter", mode = "Search|Vi", action = "ReceiveChar"},
	{ key = "Escape", mode = "Search", action = "ReceiveChar"},
	{ key = "C", mods = "Control", mode = "Search", action = "ReceiveChar"},
	{ key = "U", mods = "Control", mode = "Search", action = "ReceiveChar"},
	{ key = "W", mods = "Control", mode = "Search", action = "ReceiveChar"},
	{ key = "P", mods = "Control", mode = "Search", action = "ReceiveChar"},
	{ key = "N", mods = "Control", mode = "Search", action = "ReceiveChar"},
	{ key = "ArrowUp", mode = "Search", action = "ReceiveChar"},
	{ key = "ArrowDown", mode = "Search", action = "ReceiveChar"},
	{ key = "Enter", mode = "Search|~Vi", action = "ReceiveChar"},
	# macOS only
	{ key = "K", mods = "Command", mode = "~Vi|~Search", action = "ReceiveChar"},
	{ key = "K", mods = "Command", mode = "~Vi|~Search", action = "ReceiveChar"},
	{ key = "0", mods = "Command", action = "ReceiveChar"},
	{ key = "=", mods = "Command", action = "IncreaseFontSize"},
	{ key = "+", mods = "Command", action = "ReceiveChar"},
	{ key = "NumpadAdd", mods = "Command", action = "ReceiveChar"},
	{ key = "-", mods = "Command", action = "DecreaseFontSize"},
	{ key = "NumpadSubtract", mods = "Command", action = "ReceiveChar"},
	# { key = "V", mods = "Command", mode = "~Vi", action = "ReceiveChar"},
	# { key = "V", mods = "Command", mode = "Vi|Search", action = "ReceiveChar"},
	# { key = "C", mods = "Command", action = "ReceiveChar"},
	{ key = "C", mods = "Command", mode = "Vi|~Search", action = "ReceiveChar"},
	{ key = "H", mods = "Command", action = "ReceiveChar"},
	{ key = "H", mods = "Command|Alt", action = "ReceiveChar"},
	{ key = "M", mods = "Command", action = "ReceiveChar"},
	{ key = "Q", mods = "Command", action = "ReceiveChar"},
	{ key = "W", mods = "Command", action = "ReceiveChar"},
	# { key = "N", mods = "Command", action = "ReceiveChar"},
	# { key = "T", mods = "Command", action = "ReceiveChar"},
	{ key = "F", mods = "Command|Control", action = "ReceiveChar"},
	{ key = "F", mods = "Command", mode = "~Search", action = "ReceiveChar"},
	{ key = "B", mods = "Command", mode = "~Search", action = "ReceiveChar"},
	{ key = "]", mods = "Command|Shift", action = "ReceiveChar"},
	{ key = "[", mods = "Command|Shift", action = "ReceiveChar"},
	{ key = "Tab", mods = "Command", action = "ReceiveChar"},
	{ key = "Tab", mods = "Command|Shift", action = "ReceiveChar"},
	{ key = "1", mods = "Command", action = "ReceiveChar"},
	{ key = "2", mods = "Command", action = "ReceiveChar"},
	{ key = "3", mods = "Command", action = "ReceiveChar"},
	{ key = "4", mods = "Command", action = "ReceiveChar"},
	{ key = "5", mods = "Command", action = "ReceiveChar"},
	{ key = "6", mods = "Command", action = "ReceiveChar"},
	{ key = "7", mods = "Command", action = "ReceiveChar"},
	{ key = "8", mods = "Command", action = "ReceiveChar"},
	{ key = "9", mods = "Command", action = "ReceiveChar"}
]
