---
name: Dotfiles testing

on:
  push:
    branches:
      - 'main'
      - 'work'
jobs:
  build:
    name: install files headless
    runs-on: macos-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v3
      - run: |
          set -eo pipefail
          export CI=1
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply jackwiseman

