---
name: Test Dotfiles (work branch)

on:
  push:

jobs:
  build:
    name: install files headless from work branch
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: remove go/gofmt symlinks
        run: |
          sudo rm /usr/local/bin/go
          sudo rm /usr/local/bin/gofmt
      - name: bootstrap
        run: |
          set -eo pipefail
          export CI=1
          git_branch=${GITHUB_REF#refs/heads/}
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --branch ${GITHUB_REF##*/} --promptBool headless=true --apply jackwiseman -k
      - name: init.lua
        run: |
          nvim --headless --clean -u $HOME/.config/nvim/init.lua +'luafile $HOME/.config/nvim/init.lua' +'qall!'
      - name: neovim healthcheck
        run: |
          nvim --headless --clean +'checkhealth' +'qa!'
