---
name: Test Dotfiles on Work Branch

on:
  push:
    branches:
      - 'work'
jobs:
  build:
    name: install files headless from work branch
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: remove go/gofmt symlinks
        run: |
          sudo rm /usr/local/bin/go
          sudo rm /usr/local/bin/gofmt
      - name: test bootstrap
        run: |
          set -eo pipefail
          export CI=1
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --branch work --promptBool headless=true --apply jackwiseman -k
